### PR TITLE
[ WDFT RMT 05-2021 ] <AnnaSun> 

### PR DESCRIPTION
**Pull request by AnnaSun919**
first iteration created

### CODE REVIEW

**Comment by AnnaSun919** [comment]
solved lab only, not yet the bonus part

**Comment by TA-Remote** [comment]
Hi Anna! You did a good job on the first iteration but you stopped too early... only the 3.1 was bonus at this point, iterations 4, 5, 6 and 7 are mandatory. Please try to do them. Don't hesitate if you have any questions.

**Comment by AnnaSun919** [comment]
sorry for missing, finished them today

**Comment by TA-Remote** [comment]
That's great Anna! Thanks for finishing the exercise!

**Pull request closed without merging**
